apiVersion: v1
kind: Pod
metadata:
  name: kube-env-missing
spec:
  containers:
  - name: kube-env-missing
    image: kube-env-missing-app:latest
    imagePullPolicy: Never
    env:
      - name: APP_MODE
        value: "production"
    ports:
    - containerPort: 8765
